name: Build App
on: [push]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Select Xcode 16
        run: sudo xcode-select -s /Applications/Xcode_16.app

      - name: Build for Mac Catalyst
        run: |
          xcodebuild build \
          -scheme "Devtools" \
          -destination "platform=macOS,variant=Mac Catalyst" \
          -derivedDataPath build \
          CODE_SIGNING_ALLOWED=NO \
          CODE_SIGNING_REQUIRED=NO

      - name: Create IPA Structure
        run: |
          mkdir -p Payload
          # البحث عن مجلد التطبيق الناتج ووضعه في بايلود
          find build -name "*.app" -exec cp -R {} Payload/ \;
          zip -r Devtools.ipa Payload

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Devtools-Package
          path: Devtools.ipa
